# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to any branch. 
# For real use you might want to restrict this to the "prod" branch.
#

name: Delete microservice

on:
  #Should work only on manual trigger
  workflow_dispatch: 

jobs:

  delete:
    #Virtual Machine Name
    runs-on: ubuntu-latest
    
    #Environment variables/github secrets
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      #Gives access to repository files
      - uses: actions/checkout@v3

      #
      # Installs Kubectl and connects it to the cluster/VM
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      #
      #Deleting the deployment resources
      - name: Delete
        run: ./scripts/delete.sh
